In [2]:
# Importa o módulo
from data_quality import DataQuality
import pandas as pd


# Carrega um DataFrame (exemplo com o dataset Titanic)
df = pd.read_csv('C:/Users/José Pedro Morgado/Desktop/aula/penguins.csv')

# Crie uma instância de DataQuality
dq = DataQuality(df)

# Gere o relatório
relatorio = dq.generate_report()

# Imprima o relatório
print(relatorio)

=== Relatório de Qualidade de Dados ===

1. Contagem de valores ausentes:
species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

2. Contagem de valores únicos:
species                3
island                 3
bill_length_mm       164
bill_depth_mm         80
flipper_length_mm     55
body_mass_g           94
sex                    2
dtype: int64

3. Contagem de valores de texto únicos:
species    3
island     3
sex        2
dtype: int64

4. Contagem de valores float únicos:
bill_length_mm       164
bill_depth_mm         80
flipper_length_mm     55
body_mass_g           94
dtype: int64

5. Contagem de valores inteiros únicos:
Series([], dtype: object)

6. Contagem de valores para colunas categóricas:

Contagem de valores para species:
species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64


Contagem de valores para island:
island
Biscoe       168
Dream        124
Torgersen     52
Name: count, dtype: int64


Contagem de valores para sex:
sex
MALE      168
FEMALE    165
Name: count, dtype: int64

7. Descrição estatística das colunas numéricas:
       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921930      17.151170         200.915205  4201.754386
std          5.459584       1.974793          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
25%         39.225000      15.600000         190.000000  3550.000000
50%         44.450000      17.300000         197.000000  4050.000000
75%         48.500000      18.700000         213.000000  4750.000000
max         59.600000      21.500000         231.000000  6300.000000